apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: testnginx:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443  
    name: https
  - port: 22
    protocol: TCP
    targetPort: 22
    name: ssh
  type: LoadBalancer
  selector:
    app: nginx
